### ISSUE TITLE
unexpected token import

### ISSUE THREAD

**Issue by daresh** [dvabuzyarov/nativescript-exit#2]
Hi, I'm trying to use your plugin, but get an error: "unexpected token import".

Any ideas?

**Comment by dvabuzyarov** [comment]
Hello, can you provide your typescript version? Are you getting it at the compile time or at the design time?

**Comment by daresh** [comment]
I'm not using typescript, it's core js. I also described it here: 
https://discourse.nativescript.org/t/unexpected-token-import/3800/2

**Comment by dvabuzyarov** [comment]
I would consider this as a solved issue. Cheers!
